---
- name: test env var
  hosts: localhost
  gather_facts: no

  tasks:
    - name: show env var
      debug:
        msg: "'{{ lookup('env', 'HASHI_VAULT_ENV') }}' is the environment variable"

    - name: show env var
      debug:
        msg: "This is from extra vars {{ ansible_hashi_vault_extravar }}"